apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.local
    - argocd-server
    - argocd-server.argocd
    - argocd-server.argocd.svc
    - argocd-server.argocd.svc.cluster.local
    - 192.168.0.215
    - 192.168.0.210
  ipAddresses:
    - 192.168.0.215
    - 192.168.0.210
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
