---
- name: Allow Kubernetes API Server (6443/tcp)
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp
    comment: "Kubernetes API Server"
  tags: firewall

- name: Allow HTTP (80/tcp)
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: "HTTP"
  tags: firewall

- name: Allow HTTPS (443/tcp)
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    comment: "HTTPS"
  tags: firewall

- name: Allow NodePort Services (30000-32767/tcp)
  community.general.ufw:
    rule: allow
    port: 30000:32767
    proto: tcp
    comment: "NodePort Services"
  tags: firewall

- name: Allow HAProxy Stats (8404/tcp)
  community.general.ufw:
    rule: allow
    port: 8404
    proto: tcp
    comment: "Kubernetes HAProxy Stats"
  tags: firewall