---
- name: Configure Firewall for Load Balancer
  include_tasks: firewall.yml
  tags: loadbalancer

- name: Fix system time (NTP sync)
  block:
    - name: Install NTP utilities
      apt:
        name:
          - chrony
          - ntpdate
        state: present
        update_cache: yes

    - name: Stop chrony service
      systemd:
        name: chrony
        state: stopped
      ignore_errors: true

    - name: Sync time with ntpdate
      command: ntpdate -s time.nist.gov
      ignore_errors: true

    - name: Set timezone to Europe/Warsaw
      timezone:
        name: Europe/Warsaw

    - name: Start and enable chrony
      systemd:
        name: chrony
        state: started
        enabled: yes

    - name: Force time synchronization
      command: chronyc sources -v
      ignore_errors: true
  tags: loadbalancer

- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present
  tags: loadbalancer

- name: Ensure HAProxy socket directory exists
  file:
    path: /run/haproxy
    state: directory
    owner: haproxy
    group: haproxy
    mode: '0755'
  tags: loadbalancer

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: 'haproxy -c -f %s'
  notify: restart_haproxy
  tags: loadbalancer

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify: restart_keepalived
  tags: loadbalancer

- name: Enable HAProxy service
  systemd:
    name: haproxy
    enabled: yes
  tags: loadbalancer

- name: Enable Keepalived service
  systemd:
    name: keepalived
    enabled: yes
  tags: loadbalancer

- name: Start HAProxy
  systemd:
    name: haproxy
    state: started
  tags: loadbalancer

- name: Start Keepalived
  systemd:
    name: keepalived
    state: started
  tags: loadbalancer