---
- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present
  tags: loadbalancer

- name: Ensure HAProxy socket directory exists
  file:
    path: /run/haproxy
    state: directory
    owner: haproxy
    group: haproxy
    mode: '0755'
  tags: loadbalancer

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: 'haproxy -c -f %s'
  notify: restart_haproxy
  tags: loadbalancer

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
  notify: restart_keepalived
  tags: loadbalancer

- name: Enable HAProxy service
  systemd:
    name: haproxy
    enabled: yes
  tags: loadbalancer

- name: Enable Keepalived service
  systemd:
    name: keepalived
    enabled: yes
  tags: loadbalancer

- name: Start HAProxy
  systemd:
    name: haproxy
    state: started
  tags: loadbalancer

- name: Start Keepalived
  systemd:
    name: keepalived
    state: started
  tags: loadbalancer