---
- name: Configure Load Balancer
  hosts: k8s_loadbalancers
  become: yes
  roles:
    - { role: common, tags: [packages, security, vagrant_removal] }
    - { role: loadbalancer, tags: [loadbalancer] }