---
- name: Configure Kubernetes worker nodes
  hosts: k8s_workers
  become: yes
  roles:
    - { role: common, tags: [packages, security, vagrant_removal] }
    - { role: k8s-worker, tags: kubernetes }
