---
# Kubernetes Disaster Recovery Configuration
cluster:
  name: "k8s-ha-cluster"
  control_plane_endpoint: "192.168.0.200:6443"
  
nodes:
  masters:
    - "k8s-master-1"
    - "k8s-master-2"
  workers:
    - "k8s-worker-1"
    - "k8s-worker-2"
  loadbalancers:
    - "k8s-lb"

backup:
  s3_bucket: "k8s-disaster-recovery-backups"
  retention_days: 30
  backup_schedule: "0 2 * * *"  # Daily at 2 AM
  
snapshots:
  retention_count: 7
  auto_cleanup: true
  
monitoring:
  health_check_interval: "0 */6 * * *"  # Every 6 hours
  slack_webhook_enabled: false
  email_notifications: false