apiVersion: v1
kind: Pod
metadata:
  name: pause-container
  labels:
    app: pause
    app.kubernetes.io/category: diagnostic
    app.kubernetes.io/component: k8s-core
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.9
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "20m"
  restartPolicy: Always
