---
extends: default
rules:
  line-length: disable
  trailing-spaces: {level: warning}
  document-start: {level: warning}
  truthy: {level: warning}
  indentation: {level: warning}
  empty-lines: {level: warning}
  comments: {level: warning}
  comments-indentation: {level: warning}
  braces: {level: warning}
  brackets: {level: warning}
