apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-kustomize
  namespace: argocd
  labels:
    app: blog
    category: demo-app
    method: kustomize
spec:
  project: default

  source:
    repoURL: https://github.com/adsz/devops-lab-repo-k8s.git
    targetRevision: WIP
    path: diagnostic_deployments/demo-app-blog/k8s/kustomize

  destination:
    server: https://kubernetes.default.svc
    namespace: kustomize

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
