apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- name: k-blog-api
  count: 3
- name: k-blog-frontend
  count: 3

patches:
- target:
    kind: ConfigMap
    name: k-blog-api-config
  patch: |-
    - op: replace
      path: /data/REDIS_HOST
      value: k-blog-cache
- target:
    kind: Secret
    name: k-blog-db-secret
  patch: |-
    - op: replace
      path: /stringData/DB_HOST
      value: k-blog-db
