apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-diagnostic.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app: mariadb
