apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-diagnostic.fullname" . }}
  labels:
    app: minio
    app.kubernetes.io/name: minio
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.apiPort }}
    targetPort: api
    protocol: TCP
    name: api
  - port: {{ .Values.service.consolePort }}
    targetPort: console
    protocol: TCP
    name: console
  selector:
    app: minio
