---
- name: Allow Kubelet API (10250/tcp)
  community.general.ufw:
    rule: allow
    port: 10250
    proto: tcp
    comment: "Kubelet API"

- name: Allow NodePort Services (30000-32767/tcp)
  community.general.ufw:
    rule: allow
    port: 30000:32767
    proto: tcp
    comment: "NodePort Services"

- name: Allow Weave Net CNI (6783/tcp,udp)
  community.general.ufw:
    rule: allow
    port: 6783
    proto: tcp
    comment: "Weave Net TCP"
- community.general.ufw:
    rule: allow
    port: 6783
    proto: udp
    comment: "Weave Net UDP"

- name: Allow Flannel VXLAN (8472/udp)
  community.general.ufw:
    rule: allow
    port: 8472
    proto: udp
    comment: "Flannel VXLAN"

- name: Allow Flannel UDP backend (8285/udp)
  community.general.ufw:
    rule: allow
    port: 8285
    proto: udp
    comment: "Flannel UDP backend"
