---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags: kubernetes

- name: Install containerd
  apt:
    name: containerd
    state: present
  tags: kubernetes

- name: Ensure containerd configuration directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  tags: kubernetes

- name: Generate containerd default config
  shell: containerd config default > /etc/containerd/config.toml
  notify: restart_containerd
  tags: kubernetes

- name: Patch containerd config for sandbox image
  replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = ".*"'
    replace: 'sandbox_image = "{{ containerd_sandbox_image }}"'
  notify: restart_containerd
  tags: kubernetes

- name: Set SystemdCgroup = true in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: restart_containerd
  tags: kubernetes

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
  tags: kubernetes

- name: Add Kubernetes apt key
  get_url:
    url: "{{ kubernetes_apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: '0644'
  tags: kubernetes

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present
    filename: kubernetes
  tags: kubernetes

- name: Install Kubernetes components
  apt:
    name:
      - kubeadm={{ kubernetes_version }}
      - kubelet={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
    state: present
    update_cache: yes
  tags: kubernetes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl
  tags: kubernetes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb > 0
  tags: kubernetes

- name: Remove swap from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*\sswap\s'
    state: absent
  tags: kubernetes

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: kubernetes

- name: Persist kernel modules
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: '0644'
  tags: kubernetes

- name: Configure sysctl for Kubernetes
  template:
    src: kubernetes-sysctl.conf.j2
    dest: /etc/sysctl.d/99-kubernetes.conf
    mode: '0644'
  tags: kubernetes

- name: Apply sysctl settings
  command: sysctl --system
  changed_when: true
  tags: kubernetes

- name: Join Kubernetes cluster
  command: /bin/bash /tmp/k8s-join-command.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
  tags: kubernetes