apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}blog-api
  namespace: {{ .Values.namePrefix }}demo-blog
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: {{ .Values.api.nodePort }}
  selector:
    app: {{ .Values.namePrefix }}blog-api
