apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}blog-cache
  namespace: {{ .Values.namePrefix }}demo-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namePrefix }}blog-cache
  template:
    metadata:
      labels:
        app: {{ .Values.namePrefix }}blog-cache
        deployment-method: helm
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --appendonly
        - "yes"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
