apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}blog-frontend
  namespace: {{ .Values.namePrefix }}demo-blog
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: {{ .Values.namePrefix }}blog-frontend
