apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app-helm
  namespace: argocd
  labels:
    app: blog-app
    deployment-method: helm
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:adsz/devops-lab-repo-k8s.git
    targetRevision: WIP
    path: diagnostic_deployments/demo-app-blog/k8s/helm/blog-app
    helm:
      releaseName: blog-app-helm
      values: |
        namePrefix: h-

        images:
          frontend:
            repository: harbor.devops-lab.cloud/k8s-diagnostic-demos/blog-frontend
            tag: "1.0"
          api:
            repository: harbor.devops-lab.cloud/k8s-diagnostic-demos/blog-api
            tag: "1.0"

        frontend:
          replicas: 2
          nodePort: 30082

        api:
          replicas: 2
          nodePort: 30052

  destination:
    server: https://kubernetes.default.svc
    namespace: h-demo-blog

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    automated:
      prune: false
      selfHeal: false
    # Manual sync - odkomentuj automated żeby włączyć auto-sync
    # automated:
    #   prune: true
    #   selfHeal: true

  revisionHistoryLimit: 3
