apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app-plain
  namespace: argocd
  labels:
    app: blog-app
    deployment-method: plain-yaml
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/adsz/devops-lab-repo-k8s.git
    targetRevision: WIP
    path: diagnostic_deployments/demo-app-blog/k8s/plain-yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-blog

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    automated:
      prune: false
      selfHeal: false
    # Manual sync - odkomentuj automated żeby włączyć auto-sync
    # automated:
    #   prune: true
    #   selfHeal: true

  revisionHistoryLimit: 3
