---
kubernetes_apt_key_url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_repo_version }}/deb/Release.key"
kubernetes_apt_repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_repo_version }}/deb/ /"