---
- name: Allow Kubernetes API server (6443/tcp)
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp
    comment: "Kubernetes API server"
  tags: firewall

- name: Allow etcd server client API (2379:2380/tcp)
  community.general.ufw:
    rule: allow
    port: 2379:2380
    proto: tcp
    comment: "etcd server client API"
  tags: firewall

- name: Allow Kubelet API (10250/tcp)
  community.general.ufw:
    rule: allow
    port: 10250
    proto: tcp
    comment: "Kubelet API"
  tags: firewall

- name: Allow kube-scheduler (10259/tcp)
  community.general.ufw:
    rule: allow
    port: 10259
    proto: tcp
    comment: "kube-scheduler"
  tags: firewall

- name: Allow kube-controller-manager (10257/tcp)
  community.general.ufw:
    rule: allow
    port: 10257
    proto: tcp
    comment: "kube-controller-manager"
  tags: firewall

- name: Allow Calico BGP (179/tcp)
  community.general.ufw:
    rule: allow
    port: 179
    proto: tcp
    comment: "Calico BGP"
  tags: firewall

- name: Allow Calico VXLAN (4789/udp)
  community.general.ufw:
    rule: allow
    port: 4789
    proto: udp
    comment: "Calico VXLAN"
  tags: firewall

- name: Allow Calico WireGuard (51820/udp)
  community.general.ufw:
    rule: allow
    port: 51820
    proto: udp
    comment: "Calico WireGuard"
  tags: firewall

- name: Allow NodeExplorer (9100/tcp)
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp
    comment: "NodeExplorer"
  tags: firewall

- name: Allow etcd metrics (2381/tcp)
  community.general.ufw:
    rule: allow
    port: 2381
    proto: tcp
    comment: "etcd metrics"
  tags: firewall
