---
# Configure Kubernetes master node with kubeadm
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags: kubernetes

- name: Install containerd
  apt:
    name: containerd
    state: present
  tags: kubernetes

- name: Ensure containerd configuration directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  tags: kubernetes

- name: Configure containerd
  template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: restart_containerd
  tags: kubernetes

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
  tags: kubernetes

- name: Add Kubernetes apt key
  apt_key:
    url: "{{ kubernetes_apt_key_url }}"
    state: present
  tags: kubernetes

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present
    filename: kubernetes
  tags: kubernetes

- name: Install Kubernetes components
  apt:
    name:
      - kubeadm={{ kubernetes_version }}.*
      - kubelet={{ kubernetes_version }}.*
      - kubectl={{ kubernetes_version }}.*
    state: present
    update_cache: yes
  tags: kubernetes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl
  tags: kubernetes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb > 0
  tags: kubernetes

- name: Remove swap from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*\sswap\s'
    state: absent
  tags: kubernetes

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: kubernetes

- name: Persist kernel modules
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: '0644'
  tags: kubernetes

- name: Configure sysctl for Kubernetes
  template:
    src: kubernetes-sysctl.conf.j2
    dest: /etc/sysctl.d/99-kubernetes.conf
    mode: '0644'
  tags: kubernetes

- name: Apply sysctl settings
  command: sysctl --system
  changed_when: true
  tags: kubernetes

- name: Initialize Kubernetes master node
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --control-plane-endpoint={{ control_plane_endpoint }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  tags: kubernetes

- name: Create kube config directory for ansible user
  file:
    path: /home/ansible/.kube
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'
  tags: kubernetes

- name: Copy admin.conf for ansible user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    owner: ansible
    group: ansible
    mode: '0600'
    remote_src: yes
  tags: kubernetes

- name: Create kube config directory for ubuntu user
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'
  tags: kubernetes

- name: Copy admin.conf for ubuntu user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: '0600'
    remote_src: yes
  tags: kubernetes

- name: Install Flannel CNI
  command: >
    kubectl apply -f {{ flannel_manifest_url }}
  environment:
    KUBECONFIG: /home/ansible/.kube/config
  when: kubeadm_init.changed
  tags: kubernetes

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  when: kubeadm_init.changed
  tags: kubernetes

- name: Save join command
  copy:
    content: "{{ join_command.stdout }}"
    dest: /home/ansible/k8s-join-command.sh
    owner: ansible
    group: ansible
    mode: '0600'
  when: join_command.changed
  tags: kubernetes
