---
# Configure Kubernetes master node
- name: Include common role for shared setup
  include_role:
    name: common
  tags: [packages, security, vagrant_removal]

- name: Configure Kubernetes master
  include_tasks: kubernetes.yml
  tags: kubernetes
