apiVersion: v1
kind: Secret
metadata:
  name: blog-db-secret
  namespace: demo-blog
type: Opaque
stringData:
  POSTGRES_DB: blogdb
  POSTGRES_USER: blog
  POSTGRES_PASSWORD: blogpass
  DB_HOST: blog-db
  DB_NAME: blogdb
  DB_USER: blog
  DB_PASS: blogpass
