---
# Common setup tasks for all nodes
- name: Update system packages
  import_tasks: packages.yml
  tags: [common, packages]

- name: Apply security hardening
  import_tasks: security.yml
  tags: [common, security]

- name: Remove vagrant user
  import_tasks: vagrant_removal.yml
  tags: [common, vagrant_removal]


