---
# Common setup tasks for all nodes
- name: Update system packages
  include_tasks: packages.yml
  tags: packages

- name: Remove vagrant user
  include_tasks: vagrant_removal.yml
  tags: vagrant_removal

- name: Apply security hardening
  include_tasks: security.yml
  tags: security
