---
# Update and upgrade system packages
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  register: apt_update
  retries: 3
  delay: 5
  until: apt_update is success
  tags: packages

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: apt_upgrade
  retries: 3
  delay: 5
  until: apt_upgrade is success
  tags: packages
